// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JfrogProject
{
    /// <summary>
    /// The provider type for the project package. By default, resources use package-wide configuration
    /// settings, however an explicit `Provider` instance may be created and passed during resource
    /// construction to achieve fine-grained programmatic control over provider settings. See the
    /// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
    /// </summary>
    [JfrogProjectResourceType("pulumi:providers:jfrog-project")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// This is a Bearer token that can be given to you by your admin under `Identity and Access`. This can also be sourced from
        /// the `PROJECT_ACCESS_TOKEN` or `JFROG_ACCESS_TOKEN` environment variable. Defauult to empty string if not set.
        /// </summary>
        [Output("accessToken")]
        public Output<string?> AccessToken { get; private set; } = null!;

        /// <summary>
        /// OIDC provider name. See [Configure an OIDC
        /// Integration](https://jfrog.com/help/r/jfrog-platform-administration-documentation/configure-an-oidc-integration) for
        /// more details.
        /// </summary>
        [Output("oidcProviderName")]
        public Output<string?> OidcProviderName { get; private set; } = null!;

        [Output("tfcCredentialTagName")]
        public Output<string?> TfcCredentialTagName { get; private set; } = null!;

        /// <summary>
        /// URL of Artifactory. This can also be sourced from the `PROJECT_URL` or `JFROG_URL` environment variable. Default to
        /// 'http://localhost:8081' if not set.
        /// </summary>
        [Output("url")]
        public Output<string?> Url { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs? args = null, CustomResourceOptions? options = null)
            : base("jfrog-project", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "accessToken",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("accessToken")]
        private Input<string>? _accessToken;

        /// <summary>
        /// This is a Bearer token that can be given to you by your admin under `Identity and Access`. This can also be sourced from
        /// the `PROJECT_ACCESS_TOKEN` or `JFROG_ACCESS_TOKEN` environment variable. Defauult to empty string if not set.
        /// </summary>
        public Input<string>? AccessToken
        {
            get => _accessToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accessToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Toggle for pre-flight checking of Artifactory Enterprise license. Default to `true`.
        /// </summary>
        [Input("checkLicense", json: true)]
        public Input<bool>? CheckLicense { get; set; }

        /// <summary>
        /// OIDC provider name. See [Configure an OIDC
        /// Integration](https://jfrog.com/help/r/jfrog-platform-administration-documentation/configure-an-oidc-integration) for
        /// more details.
        /// </summary>
        [Input("oidcProviderName")]
        public Input<string>? OidcProviderName { get; set; }

        [Input("tfcCredentialTagName")]
        public Input<string>? TfcCredentialTagName { get; set; }

        /// <summary>
        /// URL of Artifactory. This can also be sourced from the `PROJECT_URL` or `JFROG_URL` environment variable. Default to
        /// 'http://localhost:8081' if not set.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public ProviderArgs()
        {
            AccessToken = Utilities.GetEnv("PROJECT_ACCESS_TOKEN", "JFROG_ACCESS_TOKEN");
            CheckLicense = false;
            Url = Utilities.GetEnv("PROJECT_URL", "JFROG_URL", "JFROG_PLATFORM_URL") ?? "http://localhost:8081";
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
