// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Pulumi.JfrogProject
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("jfrog-project");

        private static readonly __Value<string?> _accessToken = new __Value<string?>(() => __config.Get("accessToken") ?? Utilities.GetEnv("PROJECT_ACCESS_TOKEN", "JFROG_ACCESS_TOKEN"));
        /// <summary>
        /// This is a Bearer token that can be given to you by your admin under `Identity and Access`. This can also be sourced from
        /// the `PROJECT_ACCESS_TOKEN` or `JFROG_ACCESS_TOKEN` environment variable. Defauult to empty string if not set.
        /// </summary>
        public static string? AccessToken
        {
            get => _accessToken.Get();
            set => _accessToken.Set(value);
        }

        private static readonly __Value<bool?> _checkLicense = new __Value<bool?>(() => __config.GetBoolean("checkLicense") ?? false);
        /// <summary>
        /// Toggle for pre-flight checking of Artifactory Enterprise license. Default to `true`.
        /// </summary>
        public static bool? CheckLicense
        {
            get => _checkLicense.Get();
            set => _checkLicense.Set(value);
        }

        private static readonly __Value<string?> _oidcProviderName = new __Value<string?>(() => __config.Get("oidcProviderName"));
        /// <summary>
        /// OIDC provider name. See [Configure an OIDC
        /// Integration](https://jfrog.com/help/r/jfrog-platform-administration-documentation/configure-an-oidc-integration) for
        /// more details.
        /// </summary>
        public static string? OidcProviderName
        {
            get => _oidcProviderName.Get();
            set => _oidcProviderName.Set(value);
        }

        private static readonly __Value<string?> _url = new __Value<string?>(() => __config.Get("url") ?? Utilities.GetEnv("PROJECT_URL", "JFROG_URL", "JFROG_PLATFORM_URL") ?? "http://localhost:8081");
        /// <summary>
        /// URL of Artifactory. This can also be sourced from the `PROJECT_URL` or `JFROG_URL` environment variable. Default to
        /// 'http://localhost:8081' if not set.
        /// </summary>
        public static string? Url
        {
            get => _url.Get();
            set => _url.Set(value);
        }

    }
}
