// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/skycaptain/pulumi-jfrog-project/sdk/go/jfrog-project/internal"
)

var _ = internal.GetEnvOrDefault

// This is a Bearer token that can be given to you by your admin under `Identity and Access`. This can also be sourced from
// the `PROJECT_ACCESS_TOKEN` or `JFROG_ACCESS_TOKEN` environment variable. Defauult to empty string if not set.
func GetAccessToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "jfrog-project:accessToken")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "PROJECT_ACCESS_TOKEN", "JFROG_ACCESS_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}

// Toggle for pre-flight checking of Artifactory Enterprise license. Default to `true`.
func GetCheckLicense(ctx *pulumi.Context) bool {
	v, err := config.TryBool(ctx, "jfrog-project:checkLicense")
	if err == nil {
		return v
	}
	var value bool
	value = false
	return value
}

// OIDC provider name. See [Configure an OIDC
// Integration](https://jfrog.com/help/r/jfrog-platform-administration-documentation/configure-an-oidc-integration) for
// more details.
func GetOidcProviderName(ctx *pulumi.Context) string {
	return config.Get(ctx, "jfrog-project:oidcProviderName")
}

// URL of Artifactory. This can also be sourced from the `PROJECT_URL` or `JFROG_URL` environment variable. Default to
// 'http://localhost:8081' if not set.
func GetUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "jfrog-project:url")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("http://localhost:8081", nil, "PROJECT_URL", "JFROG_URL", "JFROG_PLATFORM_URL"); d != nil {
		value = d.(string)
	}
	return value
}
