# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

accessToken: Optional[str]
"""
This is a Bearer token that can be given to you by your admin under `Identity and Access`. This can also be sourced from
the `PROJECT_ACCESS_TOKEN` or `JFROG_ACCESS_TOKEN` environment variable. Defauult to empty string if not set.
"""

checkLicense: bool
"""
Toggle for pre-flight checking of Artifactory Enterprise license. Default to `true`.
"""

oidcProviderName: Optional[str]
"""
OIDC provider name. See [Configure an OIDC
Integration](https://jfrog.com/help/r/jfrog-platform-administration-documentation/configure-an-oidc-integration) for
more details.
"""

tfcCredentialTagName: Optional[str]

url: str
"""
URL of Artifactory. This can also be sourced from the `PROJECT_URL` or `JFROG_URL` environment variable. Default to
'http://localhost:8081' if not set.
"""

