// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("jfrog-project");

/**
 * This is a Bearer token that can be given to you by your admin under `Identity and Access`. This can also be sourced from
 * the `PROJECT_ACCESS_TOKEN` or `JFROG_ACCESS_TOKEN` environment variable. Defauult to empty string if not set.
 */
export declare const accessToken: string | undefined;
Object.defineProperty(exports, "accessToken", {
    get() {
        return __config.get("accessToken") ?? utilities.getEnv("PROJECT_ACCESS_TOKEN", "JFROG_ACCESS_TOKEN");
    },
    enumerable: true,
});

/**
 * Toggle for pre-flight checking of Artifactory Enterprise license. Default to `true`.
 */
export declare const checkLicense: boolean;
Object.defineProperty(exports, "checkLicense", {
    get() {
        return __config.getObject<boolean>("checkLicense") ?? false;
    },
    enumerable: true,
});

/**
 * OIDC provider name. See [Configure an OIDC
 * Integration](https://jfrog.com/help/r/jfrog-platform-administration-documentation/configure-an-oidc-integration) for
 * more details.
 */
export declare const oidcProviderName: string | undefined;
Object.defineProperty(exports, "oidcProviderName", {
    get() {
        return __config.get("oidcProviderName");
    },
    enumerable: true,
});

export declare const tfcCredentialTagName: string | undefined;
Object.defineProperty(exports, "tfcCredentialTagName", {
    get() {
        return __config.get("tfcCredentialTagName");
    },
    enumerable: true,
});

/**
 * URL of Artifactory. This can also be sourced from the `PROJECT_URL` or `JFROG_URL` environment variable. Default to
 * 'http://localhost:8081' if not set.
 */
export declare const url: string;
Object.defineProperty(exports, "url", {
    get() {
        return __config.get("url") ?? (utilities.getEnv("PROJECT_URL", "JFROG_URL", "JFROG_PLATFORM_URL") || "http://localhost:8081");
    },
    enumerable: true,
});

