// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JfrogProject.Inputs
{

    public sealed class ProjectGroupArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Must be existing Artifactory group
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("roles", required: true)]
        private InputList<string>? _roles;

        /// <summary>
        /// List of pre-defined Project or custom roles
        /// </summary>
        public InputList<string> Roles
        {
            get => _roles ?? (_roles = new InputList<string>());
            set => _roles = value;
        }

        public ProjectGroupArgs()
        {
        }
        public static new ProjectGroupArgs Empty => new ProjectGroupArgs();
    }
}
