// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.JfrogProject.Inputs
{

    public sealed class ProjectAdminPrivilegeGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enables a project admin to define the resources to be indexed by Xray
        /// </summary>
        [Input("indexResources", required: true)]
        public Input<bool> IndexResources { get; set; } = null!;

        /// <summary>
        /// Allows the Project Admin to manage Platform users/groups as project members with different roles.
        /// </summary>
        [Input("manageMembers", required: true)]
        public Input<bool> ManageMembers { get; set; } = null!;

        /// <summary>
        /// Allows the Project Admin to manage resources - repositories, builds and Pipelines resources on the project level.
        /// </summary>
        [Input("manageResources", required: true)]
        public Input<bool> ManageResources { get; set; } = null!;

        public ProjectAdminPrivilegeGetArgs()
        {
        }
        public static new ProjectAdminPrivilegeGetArgs Empty => new ProjectAdminPrivilegeGetArgs();
    }
}
